name:                brainfuck
version:             0.1.0.0
github:              "ydm/brainfuck"
license:             BSD3
author:              "Yordan Miladinov"
maintainer:          "jordanMiladinov@gmail.com"
copyright:           "Copyleft"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Stuff

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ydm/brainfuck#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  brainfuck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wextra
    dependencies:
    - brainfuck
    - vector

tests:
  brainfuck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainfuck
